### ISSUE TITLE
Add telegram button to site header

### ISSUE THREAD

**Issue by dtquandt** [Paratii-Video/paratiisite#105]
![image](https://user-images.githubusercontent.com/22087080/40862796-0759697c-65c4-11e8-8bc5-0a141fa0d501.png)

A button such as the one in the image above, linking to the relevant Telegram group for the selected language (ie: t.me/paratiivideo for PT, https://t.me/joinchat/EWZMBQ9mnqJ1--NKHpyF8A for the rest) would be nice to have and should help us grow the community.

**Comment by felipegaucho** [comment]
Do we have a design @dtquandt ?

**Comment by dtquandt** [comment]
We do now! Thanks @pedrocasa.

https://xd.adobe.com/view/b9496c23-b7b5-40e0-9998-665a795b71ed

**Comment by felipegaucho** [comment]
Isn't it too big / long @pedrocasa @dtquandt ?
"Join Telegram", "Join Community", "Come to the family", "Participate" - all could be shorter.
The purple against purple doesn't really do much, IMHO, too. Sorry for being picky 🙈

**Comment by dtquandt** [comment]
It's big, but I thought the idea was to call attention to it - otherwise "Join us on Telegram" is fine, for instance.

**Comment by pedrocasa** [comment]
links updated

**Comment by dtquandt** [comment]
I see the button is already on the website but it doesn't adapt to language changes or change the link to the Brazilian group when in Portuguese. Can we at least have it link to t.me/paratiivideo when in the PT mode, @jrgarou ?

**Comment by felipegaucho** [comment]
@jrgarou I did the updates some hours ago, seems to not have gone through tho. Maybe something w/ the new Telegram button element?
