### ISSUE TITLE
(ATBlock) Minor improvements

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratiisite#12]
- [x] animações dos blocos
- [x] animação typewriter com as palavras na seção inicial
- [x] diminuir pela metade a largura do menu lateral aberto no desktop
- [x] cadeado ou equivalente sobre os posters, quando se clica (em substituição ao "not available")
- [x] feedback (carregamento e volume?) nos vídeos/teasers
- [x] as palavras chapters estão sumindo no mobile
- [x] resolver de outra maneira o twitter/github dos profiles para não prejudicar a pagina Charlie/ Anthony
- [x] mudar os teasers, ( o site deve abrir com o teaser 2 ( Alex Van de Sande ) , o teaser 1 ( Sergio Lerner) deve aparecer quando clicar no "next teasers"
- [x] O html `<video>` no Android tem problemas para "_alcançar_" o `readyState == 4`. 
Modificar a detecção desse `state` nos vídeos do teaser.

**Comment by jrgarou** [comment]
`feedback (carregamento e volume?) nos vídeos/teasers`
@felipegaucho como vai ser esse feedback(design)? Acredito que um _loader_(spinner talvez) para o carregamento.

Sobre o volume, é um mute ou slide?

**Comment by pedrocasa** [comment]
@jrgarou  Eu acho que consegui resolver uma solução de design para resolver o sétimo "issue" no atomic.io, ( https://app.atomic.io/d/69O0dUhx4R5Q )

O que vai mudar: 
1- Não vai mais haver quebras de linha nomes
2- Diminuir o tamanho do corpo de letra dos nomes
3- Novos botões de twitter e github , vão ficar em baixo de cada nome

**Comment by jrgarou** [comment]
@felipegaucho @pedrocasa , _chequei_ o que foi feito até então. 
Tanto os cubos quanto o typewrite estão funcionando http://paratii.video/around-the-block/

@pedrocasa, hoje às 19hs farei a sua sugestão do [comentário acima](https://github.com/Paratii-Video/paratiisite/issues/12#issuecomment-325758542). Também o ajuste no video para android.

por favor, dêem uma olhada nesse comentário: https://github.com/Paratii-Video/paratiisite/issues/12#issuecomment-325707483

**Comment by felipegaucho** [comment]
@jrgarou achei mto elegante o typewriter e os cubos.
feedback: um loader discreto que tu pode escolher um existente e passar pelo crivo/tapa do pedro (mais prático do que fazer um) + [ícone de volume](https://github.com/Paratii-Video/paratii-player/blob/c132263877e1e101a41e35e874386e67313741ca/public/img/volume-icon.svg) / [mutado](https://github.com/Paratii-Video/paratii-player/blob/0e4bfe45f6e8adc14ac1b1fa3071741f5f9c47fd/public/img/mute-icon.svg) + um slider. Podemos pegar [slider que já está no player](https://github.com/Paratii-Video/paratii-player/blob/934575a7b2f70cf086868574de8b3168a814e6e4/imports/ui/pages/player/player.js)(linha ~145 do link).

**Comment by jrgarou** [comment]
@felipegaucho @lupape @pedrocasa Fiz um update no site.

Temos:
- todas as imagens e vídeos do site estão no amazon;
- largura do menu lateral aberto no desktop ajustada;
- cadeado nos posters de **chapters** (vi agora que o "not available" permanece. Vou retirar);
- botões de social em **interviews** 
- ordem dos teasers;
- video rodando no android.

@pedrocasa o logo mobile está no [servidor da amazon](https://s3.console.aws.amazon.com/s3/object/paratiivideo/around-the-block/images/intro/logo-around-the-block-mobile.png). Vamos subir um com a cor do fundo aplicado.
