### ISSUE TITLE
ATB is too slow

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratiisite#13]
@jrgarou 

Quando acessado pela primeira vez, o site Around The Block demora muito para responder.  Aproximadamente 10 segundos para a animação do logo começar a rodar ( primeira imagem)

![image](https://user-images.githubusercontent.com/30123644/29837828-b422a11a-8ccf-11e7-9d30-99b063bad797.png)

Após isso a animação fica mais alguns segundos travada  (segunda imagem)  e depois o site  roda normalmente

![image](https://user-images.githubusercontent.com/30123644/29836819-bc2c7b22-8ccc-11e7-8b7e-c7451d2ebd1b.png)

Não sei se isso acontece devido ao tamanho da animação ou por algum outro problema no processamento

**Comment by pedrocasa** [comment]
@jrgarou

**Comment by jrgarou** [comment]
@pedrocasa Não é um problema de processamento, o vídeo demora pra carregar. Ele atualmente tem 1mb. Vale lembrar também que temos as imagens do site sendo carregadas. 

Seria interessante se conseguíssemos optimizar esse video o máximo que pudermos.

![image](https://user-images.githubusercontent.com/320157/29842154-6161f7c8-8cde-11e7-8820-73687ccd661c.png)

**Comment by jrgarou** [comment]
@pedrocasa podemos também rever a otimização das imagens.
Eu utilizei um otimizador automático(`gulp-imagemin`), mas eles não são 100% confiáveis. O ideal é verificar uma a uma o que é possível fazer de compressão sem perder a qualidade - algumas cores podem perder detalhes.

Existem algumas ferramentas pra ajudar, como o https://tinypng.com/.  É sempre bom verificar se não houve perda na qualidade, mas no geral ele faz uma boa otimização.

**Comment by pedrocasa** [comment]
@jrgarou  Ontem eu subi as imagens ( github)  e os vídeos ( amazon)  já otimizados
