### ISSUE TITLE
Implement "Try the alpha version of the portal"

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratiisite#142]
We need a "Try the alpha version of the portal" in order for our visitors can find our platform, here is the design of it

![web 1920 7](https://user-images.githubusercontent.com/30123644/42063609-e1740c58-7b08-11e8-9350-6731b7217a33.png)

dropbox: https://www.dropbox.com/home/paratii-design/master?preview=site-tryalphabutton.xd

- Also, I removed the red background of the telegram button, The whole page was becoming too colourfull and less usable with all these new buttons.

**Comment by dtquandt** [comment]
We're still reviewing the design
