### ISSUE TITLE
Site Fixes

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratiisite#143]
- [x] Add a "try the alpha portal" button.

- [x] Change the first title size for title-main

- [ ] Change the first text size for text-main

- [x] Remove the subscribe form (button only)

- [ ] Increase the height of the background of the first banner (840px)

![1440 7](https://user-images.githubusercontent.com/30123644/42345101-b34b3d3a-8074-11e8-8bcb-fab5b89542c7.png)

**Comment by jrgarou** [comment]
>  Increase the height of the background of the first banner (840px)

@pedrocasa 840px is too hight. What is the purpose of this?

**Comment by jrgarou** [comment]
> Change the first text size for text-main

@pedrocasa this text is already `.text-main`
https://github.com/Paratii-Video/paratiisite/blob/221316436e66e88329e51f320ddbfe19692fbeff/src/website/styles/sections/header.scss#L105-L107

**Comment by pedrocasa** [comment]
- The Telegram button should have the #E13D84 background

- The background height is enough
