### ISSUE TITLE
Add new interviewees to ATB website

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratiisite#149]
@jrgarou all missing names & info. are below. @pedrocasa , please post/link the related assets, let's do it :)

------------------

### Anthony di Iorio (already, there, but coupled - must split)
**Co-founder of Ethereum, CEO @ Jaxx**
Former Chief Digital Officer of the Toronto Stock Exchange, di Iorio was one of the responsible people for funding early development of Ethereum before leading Jaxx and Decentral.

### Charlie Shrem (already, there, but coupled - must split)
**Co-founder @ BitInstant, COO @ Jaxx**
Charlie's story is mixed with that of Bitcoin itself. Currently leading operations @ Jaxx, he's been through a conviction, mainstream fame and a series of crypto businesses. 

### Ashley Tyson
**Partnerships and Strategic Initiatives, Web3 Foundation**
Having been involved with Bitcoin and cryptocurrencies from early on, Ashley leads the Web3 foundation's strategic efforts and is an active voice when it comes to governance in the Ethereum community.
_Twitter: https://twitter.com/AsherT/_

### ~Augusto Hack~
(não aparece na série)
~**Software Engineer @ BrainBot**~
~Backend developer, Brazilian, working on payment channels in the Raiden projects.~
~_Github: https://github.com/hackaugusto_~

### Omar Bhan
**Crypt0 - Opinion Maker**
YouTube channel host, entertainer, actor, ushering in the future through exposing financial/political corruption, truth, justice, and freedom.
_Youtube: https://www.youtube.com/channel/UCdUSSt-IEUg2eq46rD7lu_g_
_Twitter: https://twitter.com/crypt0snews_

### Dina Carabas
**Board member at Web3 Foundation**
Ex-McKinsey, Dina has been helping launch Polkadot and spearheading the Web3 Foundation's business efforts.

### Eric Tang
**CTO @ Livepeer**
Carnegie Mellon alumni, previously CTO at Wildcard, building decentralised live streaming on the Ethereum blockchain.
_Twitter: https://twitter.com/ericxtang_
_Github: https://github.com/ericxtang_

### Felipe Santana
**Project Lead @ Paratii**
Crowdfunding pioneer in Brazil, ex-Endeavor & BossaNovaFilms
_Twitter: https://twitter.com/Felipether_

### Jelle Gerbrandy
**CTO @ Paratii**
A Ph.D. in Logic, visiting scholar at Stanford, Jelle was previously the CTO at Backfeed, has written contracts for projects in the space, and leads the technical team at Paratii.
_Github: https://github.com/jellegerbrandy_

### Marco Canut
**Co-founder & CTO @ Coinwise**
Computer security specialist, cryptocurrencies advocate. Ex-CTO of Tempest Security Technologies, almost two-decade experience in infrastructure and computer security.
_Github: https://github.com/marcocarnut_

### Michael Thuy
**System Architect @ Swarm City**
Information architect and developer, Michael is an early member of the Ethereum community and is developing peer-to-peer infrastructure for desintermediated transportation services.
_Github: https://github.com/kingflurkel_
_Twitter: https://twitter.com/kingflurkel_

### Peter Czaban and Marek Kotewicz
**Executive Director @ Web3 Foundation and Core Developer @ Parity**
Peter and Marek are two of names responsible for bringing the Polkadot project to life, just as other ambitious projects held by Parity Technologies, such as the Substrate toolkit.
_Github: https://github.com/debris_

### Robert Habermeier
Polkadot co-founder, pioneering parachain research & development, Thiel Fellow, Robert is one among the sharpest young minds in the space.
_Twitter: https://twitter.com/rphmeier_
_Github: https://github.com/rphmeier_

### Fernando Ulrich
**Cryptocurrency Researcher @ XP Investimentos**
Brazil's leading authority on the economy of crypto-assets, Fernando hosts an influential YouTube channel on investment and Bitcoin.
_Twitter: https://twitter.com/fernandoulrich_

### Rosine Kadamani
**Founder of Blockchain Academy**
Lawyer for 13 years in a previous life. Specialized in Banking Law, has taught courses for the Central Bank of Brazil, the Securities and Exchange Commission, foreign authorities such as the Financial Intelligence Unit of Mauritius, as well as large banks and other companies, and students from the most influential universities in the country.
_Twitter: https://twitter.com/rosinekadamani_

### Zooko Wilcox
**Founder of Zcash**
Zooko is recognized for his work on DigiCash, Mojo Nation, ZRTP, “Zooko's Triangle”, Tahoe-LAFS, BLAKE2, and SPHINCS. He has more than 20 years of experience in open, decentralized systems, cryptography and information security, and is also the Founder of Least Authority. He likes to blog about health science. 
_Github: https://github.com/zooko_
_Twitter: https://twitter.com/zooko_

**Comment by pedrocasa** [comment]
The other assets are in the dropbox master ( I 've already shared with @jrgarou ).

I also created a l temporary link on the wetransfer https://we.tl/nMp1Zdvbvy

**Comment by pedrocasa** [comment]
@felipegaucho  if Hugo Hack is going to leave it is better to separate Peter Czaban and Marek Kotewicz for the sake of layout

**Comment by pedrocasa** [comment]
@felipegaucho The ''subtitle'' of Robert Habermeier is missing

**Comment by pedrocasa** [comment]
![screen shot 2018-08-13 at 17 08 10](https://user-images.githubusercontent.com/30,123644/44055338-7f0e8ae8-9f1b-11e8-8a30-79d165d6e27d.png)



it's a bit bigger than the portal one. tell me what you guys think about.


Also it would be better if we align the ''around the block'' logo to the center

**Comment by felipegaucho** [comment]
Either we leave one square empty, or we bring back Charlie Shrem and AnthonyDiIorio together. No more rewritings :))

**Robert Habermeier**
Co-founder of Polkadot

(the missing subtitle)

**Comment by pedrocasa** [comment]
Sure.

Let's keep  Peter Czaban and Marek Kotewicz together than
