### ISSUE TITLE
white on white text issue on iOS and chrome

### ISSUE THREAD

**Issue by nkk244** [Paratii-Video/paratiisite#15]
<img width="1243" alt="screen shot 2017-10-25 at 17 47 23" src="https://user-images.githubusercontent.com/33119650/32046681-b8bdbc9a-ba11-11e7-9e41-1f6ba22cfdaa.png">
@jrgarou 
please see screenshot :)
![image uploaded from ios](https://user-images.githubusercontent.com/33119650/32046625-993b19da-ba11-11e7-94db-5fc4ee778e22.png)

**Comment by jrgarou** [comment]
@nkk244 What URL is that? Can you give me more details?

**Comment by nkk244** [comment]
http://paratii.video/

**Comment by jrgarou** [comment]
@nkk244 there's a declaration for it http://paratii.video/css/style.css
![image](https://user-images.githubusercontent.com/320157/32177082-79b4a16e-bd70-11e7-9db4-dbc483236f39.png)

**Comment by felipegaucho** [comment]
Solved.
