### ISSUE TITLE
Implement FAQ on website

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratiisite#30]
Here is the link to the Adobe specs file for the faq page

https://xd.adobe.com/spec/0fda4288-ef30-4922-ae58-fe1b9f9d1707/#screen/c5e03fcd-c430-439a-b3c3-ace5fca2200b/P01_1920%20%E2%80%93%202

**Comment by jrgarou** [comment]
PT: https://docs.google.com/document/d/1cPFuLRoNzf0qdk1YVXM3o-anhXLyvAfmxi4ITwJeQms
EN: https://docs.google.com/document/d/1DbhapAMLoa1L7qCvihQalz4L8fuI2Ay-ZGe1NP5Ca2g/

**Comment by jrgarou** [comment]
FAQ done
https://paratii.video/faq/
