### ISSUE TITLE
Use videos of paratii instead of youtube 

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratiisite#35]
Change the youtube videos that we have on paratii.video for videos on our new platform.

**Comment by jrgarou** [comment]
@felipegaucho @felipegaucho could send the videos urls (`https://portal.paratii.video/embed/N7Hic8d0yNst`)

**Comment by felipegaucho** [comment]
In the same order,

https://portal.paratii.video/embed/akX1Cvz1G7In

https://portal.paratii.video/embed/2tfgCqOQgASU

https://portal.paratii.video/play/b9yOYeQrYIxR

**Comment by jrgarou** [comment]
@felipegaucho o segundo video(https://portal.paratii.video/embed/2tfgCqOQgASU) não está rolando

**Comment by jrgarou** [comment]
@geckoslair @jellegerbrandy
The  `autoplay=0` from `paratii-embed` it always play the video: https://jsfiddle.net/garou/yvndabg8/

`<iframe webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" src="https://portal.paratii.video/embed/akX1Cvz1G7In?autoplay=0&loop=1&playsinline=1&fullscreen=1&type=mini" width="570" height="320" frameborder="0"></iframe>`

**Comment by jellegerbrandy** [comment]
ok can you make an issue for that in the paratii-portal?

**Comment by jrgarou** [comment]
Done https://github.com/Paratii-Video/paratii-portal/issues/382

**Comment by felipegaucho** [comment]
Since this is corrected, we could proceed w/ it now, what do you think @jrgarou @pedrocasa ?

**Comment by jrgarou** [comment]
@felipegaucho Yes! I need to make some changes to fix scroll issues on embed player first.

**Comment by felipegaucho** [comment]
Tks @jrgarou !
