### ISSUE TITLE
Replace static token image with motion (mp4)

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratiisite#64]
Alecrim has done a motion to replace the static image below:

<img width="1253" alt="screen shot 2018-04-18 at 1 03 04 am" src="https://user-images.githubusercontent.com/26517120/38911473-fd2d752e-42a5-11e8-95c2-aa6d6a0db719.png">

It is here: https://drive.google.com/file/d/1wcumJkJdufvxXnshE6LY_sQ4LSimdAze/view?usp=sharing

Let's replace it on desktop only, leaving the static version for mobile? (~60% of our site's users access on desktop)

**Comment by jrgarou** [comment]
@felipegaucho It's nice. But we need to crop at the circle bounds to avoid the purple thin line:
![paratii-site-components](https://user-images.githubusercontent.com/320157/38951546-5e8fddb0-431f-11e8-956a-76eefffafa56.gif)

**Comment by felipegaucho** [comment]
too bad if we just keep it?
Doesn't look bad here
