### ISSUE TITLE
Evento - Google Analytics

### ISSUE THREAD

**Issue by rdilello** [Paratii-Video/paratiisite#65]
Oi, @jrgarou! Tudo bem?

Você poderia implementar o seguintes scripts nos botões de ação do site de Paratii?

Este script é do Google Analytics e vamos acompanhar o número de usuários que solicita cada ação. O script precisa estar dentro do botão, assim cada vez que alguém clicar acompanhamos esta ação.

[GA - Evento - Subscribe.txt](https://github.com/Paratii-Video/paratiisite/files/1925777/GA.-.Evento.-.Subscribe.txt)
[GA - Evento - Buyers & Investors.txt](https://github.com/Paratii-Video/paratiisite/files/1925778/GA.-.Evento.-.Buyers.Investors.txt)
[GA - Evento - Community.txt](https://github.com/Paratii-Video/paratiisite/files/1925779/GA.-.Evento.-.Community.txt)
[GA - Evento - Creators.txt](https://github.com/Paratii-Video/paratiisite/files/1925780/GA.-.Evento.-.Creators.txt)
[GA - Evento - Publishers.txt](https://github.com/Paratii-Video/paratiisite/files/1925781/GA.-.Evento.-.Publishers.txt)

Qualquer dúvida estou à disposição.

Obrigado e abraços.

**Comment by jrgarou** [comment]
@rdilello só pra evitarmos ter que baixar diversos arquivos, vou colar os códigos aqui para ajudar a encontrar/discutir algum problema. 

### Subscribe
```
ga('send', {
  hitType: 'event',
  eventCategory: 'Subscribe',
  eventAction: 'Enviar',
  eventLabel: 'Site',
  eventValue: '100'
});
```

### Publishers
```
ga('send', {
  hitType: 'event',
  eventCategory: 'Publishers',
  eventAction: 'Enviar',
  eventLabel: 'Site',
  eventValue: '100'
});
```

### Creators
```
ga('send', {
  hitType: 'event',
  eventCategory: 'Creators',
  eventAction: 'Enviar',
  eventLabel: 'Site',
  eventValue: '100'
});
```

### Community
```
ga('send', {
  hitType: 'event',
  eventCategory: 'Community',
  eventAction: 'Enviar',
  eventLabel: 'Site',
  eventValue: '100'
});
```

### Buyers-Investors
```
ga('send', {
  hitType: 'event',
  eventCategory: 'Buyers-Investors',
  eventAction: 'Enviar',
  eventLabel: 'Site',
  eventValue: '100'
});
```

**Comment by jrgarou** [comment]
@rdilello só temos um formulario(**subscribe** no topo) no site. Do que se trata essas outras ações?

**Comment by rdilello** [comment]
São as ações referentes as audiências - creators, publishers e community, que levam para o Google Form. Mas vamos medir somente o clique no botão que leva ao form. E tem mais aquele form para media buyers e investors.
