### ISSUE TITLE
Create campaign page

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratiisite#83]
Here are the layouts for the paratii campaign.

prototype
https://xd.adobe.com/view/e7235d68-145f-430b-b624-ad2aedd4d4bb?fullscreen

db (for develop)

https://www.dropbox.com/home/paratii-design/master/campanha

**Comment by dtquandt** [comment]
I'll send you a couple alterations in the text and the English translation 👍

**Comment by dtquandt** [comment]
https://docs.google.com/document/d/1_LmgbnKaE2w0fLkHn_ynBj94FRs5_g4WA1_dsrJKrp8/edit

This is the up-to-date text doc for the landing page.
